# Generated by Django 5.0.2 on 2024-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempid', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='mlmodel/images/')),
            ],
        ),
    ]
